USE [master]
GO

/****** Object:  Database [AwesomeTaskList]    Script Date: 21/11/2018 7:20:25 πμ ******/
CREATE DATABASE [AwesomeTaskList]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AwesomeTaskList', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\AwesomeTaskList.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AwesomeTaskList_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\AwesomeTaskList_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [AwesomeTaskList] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AwesomeTaskList].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AwesomeTaskList] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET ARITHABORT OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AwesomeTaskList] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AwesomeTaskList] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AwesomeTaskList] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AwesomeTaskList] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AwesomeTaskList] SET  MULTI_USER 
GO

ALTER DATABASE [AwesomeTaskList] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AwesomeTaskList] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AwesomeTaskList] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AwesomeTaskList] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AwesomeTaskList] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AwesomeTaskList] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AwesomeTaskList] SET  READ_WRITE 
GO

